# docker-compose.yml
#version: '3.8'

services:
  redis:
    image: redis:6-alpine
    # No need to map ports to the host anymore unless for debugging
    ports:
      - "6379:6379"

  web:
    build: .
    # No need to map ports to the host anymore
    ports:
      - "8000:8000"
    command: gunicorn --bind 0.0.0.0:8000 api.wsgi:application
    #command: > # Command to run inside the container
    #  sh -c "/usr/bin/gunicorn --bind 0.0.0.0:8000 api.wsgi:application"
    volumes:
      - .:/app # Or specifically mount only necessary code for production
    env_file:
      - .env
    depends_on:
      - redis
    restart: always # Ensure the container restarts if it crashes

  worker:
    build: .
    command: celery -A api worker -l info --uid=nobody --gid=nogroup
    volumes:
      - .:/app # Or specifically mount only necessary code for production
    env_file:
      - .env
    depends_on:
      - redis
    restart: always # Ensure the container restarts if it crashes

  nginx:
    image: nginx:alpine
    ports:
      - "80:80" # Map host port 80 to container port 80
      # - "443:443" # Uncomment if using SSL
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro # Mount our Nginx config
      # Optional: Mount static files if serving from Nginx
      # - ./staticfiles:/app/staticfiles:ro # Should match STATIC_ROOT
    depends_on:
      - web # Ensure web app is ready before Nginx
    restart: always # Ensure the container restarts if it crashes

# Optional: Define a volume for Redis data persistence (highly recommended for prod)
volumes:
  redis_data:


